name: "Update Pull Request"

on:
- pull_request

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            github.pulls.updateBranch({
              context.repo.owner,
              context.repo.name,
              context.payload.pull_request.number
            }).then(result => {}, error => console.log(error))
